language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo fmt -- --check
  - cargo test --verbose
  - cargo test --no-default-features --features=runtime-async-std --verbose
  - cargo clippy --all-targets
  - cargo clippy --all-targets --no-default-features --features=runtime-async-std
